//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.26 at 02:42:55 PM TRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mehmetnuri.com/spring-boot-soap-web-service-demo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mehmetnuri.spring_boot_soap_web_service_demo;
